require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::LayersController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Layer. As you add validations to Admin::Layer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::LayersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_layers as @admin_layers" do
      layer = Admin::Layer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_layers).should eq([layer])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_layer as @admin_layer" do
      layer = Admin::Layer.create! valid_attributes
      get :show, {:id => layer.to_param}, valid_session
      assigns(:admin_layer).should eq(layer)
    end
  end

  describe "GET new" do
    it "assigns a new admin_layer as @admin_layer" do
      get :new, {}, valid_session
      assigns(:admin_layer).should be_a_new(Admin::Layer)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_layer as @admin_layer" do
      layer = Admin::Layer.create! valid_attributes
      get :edit, {:id => layer.to_param}, valid_session
      assigns(:admin_layer).should eq(layer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Layer" do
        expect {
          post :create, {:admin_layer => valid_attributes}, valid_session
        }.to change(Admin::Layer, :count).by(1)
      end

      it "assigns a newly created admin_layer as @admin_layer" do
        post :create, {:admin_layer => valid_attributes}, valid_session
        assigns(:admin_layer).should be_a(Admin::Layer)
        assigns(:admin_layer).should be_persisted
      end

      it "redirects to the created admin_layer" do
        post :create, {:admin_layer => valid_attributes}, valid_session
        response.should redirect_to(Admin::Layer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_layer as @admin_layer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Layer.any_instance.stub(:save).and_return(false)
        post :create, {:admin_layer => {  }}, valid_session
        assigns(:admin_layer).should be_a_new(Admin::Layer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Layer.any_instance.stub(:save).and_return(false)
        post :create, {:admin_layer => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_layer" do
        layer = Admin::Layer.create! valid_attributes
        # Assuming there are no other admin_layers in the database, this
        # specifies that the Admin::Layer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Layer.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => layer.to_param, :admin_layer => { "these" => "params" }}, valid_session
      end

      it "assigns the requested admin_layer as @admin_layer" do
        layer = Admin::Layer.create! valid_attributes
        put :update, {:id => layer.to_param, :admin_layer => valid_attributes}, valid_session
        assigns(:admin_layer).should eq(layer)
      end

      it "redirects to the admin_layer" do
        layer = Admin::Layer.create! valid_attributes
        put :update, {:id => layer.to_param, :admin_layer => valid_attributes}, valid_session
        response.should redirect_to(layer)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_layer as @admin_layer" do
        layer = Admin::Layer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Layer.any_instance.stub(:save).and_return(false)
        put :update, {:id => layer.to_param, :admin_layer => {  }}, valid_session
        assigns(:admin_layer).should eq(layer)
      end

      it "re-renders the 'edit' template" do
        layer = Admin::Layer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Layer.any_instance.stub(:save).and_return(false)
        put :update, {:id => layer.to_param, :admin_layer => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_layer" do
      layer = Admin::Layer.create! valid_attributes
      expect {
        delete :destroy, {:id => layer.to_param}, valid_session
      }.to change(Admin::Layer, :count).by(-1)
    end

    it "redirects to the admin_layers list" do
      layer = Admin::Layer.create! valid_attributes
      delete :destroy, {:id => layer.to_param}, valid_session
      response.should redirect_to(admin_layers_url)
    end
  end

end
