# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ak.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-al.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ar.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-az.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ca.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-co.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ct.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-dc.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-fl.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ga.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-hi.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ia.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-id.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-il.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-in.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ks.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ky.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-la.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ma.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-md.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-me.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-mi.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-mn.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-mo.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ms.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-mt.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-nc.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ne.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-nj.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-nm.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-nv.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ny.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-oh.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-or.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-pa.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ri.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-tn.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-tx.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-ut.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-va.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-wa.sql"))
ActiveRecord::Base.connection.execute(IO.read("db/sql/areas-wi.sql"))